// Event emitter implementation 2
// Event emitter implementation 3
// Event emitter implementation 4
// Event emitter implementation 5
// Event emitter implementation 6
// Event emitter implementation 7
// Event emitter implementation 8
// Event emitter implementation 9
// Event emitter implementation 10
